-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."MyFactTrips"
(
    Tripid integer NOT NULL,
    Dateid integer NOT NULL,
    Stationid integer NOT NULL,
    Truckid integer NOT NULL,
    Wastecollected integer NOT NULL,
    PRIMARY KEY (Tripid)
);

CREATE TABLE public."MyDimDate"
(
    Dateid integer NOT NULL,
    Date date NOT NULL,
    year integer NOT NULL,
    month integer NOT NULL,
    monthname "char" NOT NULL,
    quarter integer NOT NULL,
    quartername "char" NOT NULL,
    day integer NOT NULL,
    weekday integer NOT NULL,
    weekdayrname "char" NOT NULL,
    PRIMARY KEY (Dateid)
);

CREATE TABLE public."MyDimWaste"
(
    Truckid integer NOT NULL,
    TruckType "char" NOT NULL,
    PRIMARY KEY (Truckid)
);

CREATE TABLE public."MyDimZone"
(
    Stationid integer NOT NULL,
    City "char" NOT NULL,
    CollectionZone "char" NOT NULL,
    PRIMARY KEY (Stationid)
);

ALTER TABLE public."MyFactTrips"
    ADD FOREIGN KEY (Dateid)
    REFERENCES public."MyDimDate" (Dateid)
    NOT VALID;


ALTER TABLE public."MyFactTrips"
    ADD FOREIGN KEY (Truckid)
    REFERENCES public."MyDimWaste" (Truckid)
    NOT VALID;

ALTER TABLE public."MyFactTrips"
    ADD FOREIGN KEY (Stationid)
    REFERENCES public."MyDimZone" (Stationid)
    NOT VALID;
    
END;